meta:
  name: 茅崎夕樱
style:
  mode: advanced
  text_wrapper:
    type: preset
    preset: corner_double
    prefix: 『
    suffix: 』
  basic:
    font_size: 39
    text_color: [255, 255, 255]
    name_font_size: 29
    name_color: [255, 0, 255]
  advanced:
    name_layers:
      茅崎夕樱:
      - text: 茅
        position: [-25, -15]
        font_color: [255, 0, 125]
        font_size: 44
      - text: 崎
        position: [18, 0]
        font_color: [255, 0, 255]
        font_size: 29
      - text: 夕
        position: [46, 0]
        font_color: [255, 0, 255]
        font_size: 29
      - text: 樱
        position: [72, 0]
        font_color: [255, 0, 255]
        font_size: 29
      default:
      - text: '{name}'
        position: [0, 0]
        font_color: [255, 0, 255]
        font_size: 29
  font_file: fonts\lolita.ttf
layout:
  stand_scale: 0.764
  stand_on_top: false
  _canvas_size: [1280, 720]
  text_area: [239, 591, 1079, 716]
  name_pos: [344, 544]
  current_portrait: 1.png
  current_background: 1.png
  stand_pos: [454, 114]
  box_pos: [0, 0]
  enable_crop: true
  crop_area: [3, 513, 1280, 717]
assets:
  dialog_box: textbox_bg.png
